-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "configuraciones" (
	"idconfiguracion" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "configuraciones_idconfiguracion_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"clave" varchar(100) NOT NULL,
	"valor" varchar(500) NOT NULL,
	"descripcion" varchar(500),
	"tipodato" varchar(50) NOT NULL,
	"fechacreacion" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"fechaultimaactualizacion" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "configuraciones_clave_key" UNIQUE("clave")
);
--> statement-breakpoint
CREATE TABLE "estados" (
	"idestado" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "estados_idestado_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nombre" varchar(50) NOT NULL,
	"descripcion" text,
	"activo" boolean DEFAULT true,
	"fechacreacion" timestamp DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "categoriasgasto" (
	"idcategoriagasto" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "categoriasgasto_idcategoriagasto_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nombre" varchar(100) NOT NULL,
	"descripcion" varchar(500),
	"color" varchar(20) DEFAULT '#6B7280',
	"idestado" integer DEFAULT 1 NOT NULL,
	"fechacreacion" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "clientes" (
	"idcliente" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "clientes_idcliente_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nombre" varchar(100) NOT NULL,
	"apellido" varchar(100),
	"direccion" varchar(200),
	"telefono" varchar(20),
	"email" varchar(100),
	"idestado" integer NOT NULL,
	"fecharegistro" timestamp DEFAULT CURRENT_TIMESTAMP,
	"fechaultimaactualizacion" timestamp DEFAULT CURRENT_TIMESTAMP,
	"notas" text
);
--> statement-breakpoint
CREATE TABLE "facturas" (
	"idfactura" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "facturas_idfactura_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"idcliente" integer,
	"nombrecliente" varchar(100),
	"telefonocliente" varchar(20),
	"idusuario" integer NOT NULL,
	"idestado" integer NOT NULL,
	"numerofactura" varchar(20) NOT NULL,
	"fechacreacion" timestamp DEFAULT CURRENT_TIMESTAMP,
	"fechaultimaactualizacion" timestamp DEFAULT CURRENT_TIMESTAMP,
	"fechaentregaestimada" date,
	"fechaentregareal" timestamp,
	"subtotal" numeric(10, 2) NOT NULL,
	"impuestos" numeric(10, 2) DEFAULT '0',
	"descuento" numeric(10, 2) DEFAULT '0',
	"total" numeric(10, 2) NOT NULL,
	"metodopago" varchar(20) DEFAULT 'efectivo',
	"notas" text,
	"montoabonado" numeric(10, 2),
	"montopendiente" numeric(10, 2),
	"idestadoentrega" integer,
	"recogidopor" varchar(200),
	"notasentrega" varchar(500),
	CONSTRAINT "facturas_numerofactura_key" UNIQUE("numerofactura"),
	CONSTRAINT "facturas_metodopago_check" CHECK ((metodopago)::text = ANY ((ARRAY['otro'::character varying, 'transferencia'::character varying, 'tarjeta'::character varying, 'efectivo'::character varying])::text[]))
);
--> statement-breakpoint
CREATE TABLE "detallefactura" (
	"iddetalle" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "detallefactura_iddetalle_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"idfactura" integer NOT NULL,
	"idprendaservicio" integer,
	"cantidad" integer DEFAULT 1 NOT NULL,
	"preciounitario" numeric(10, 2) NOT NULL,
	"subtotal" numeric(10, 2) GENERATED ALWAYS AS (((cantidad)::numeric * preciounitario)) STORED,
	"descripcion" text,
	"fechacreacion" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"idproducto" integer,
	"tipoitem" varchar(50) GENERATED ALWAYS AS (
CASE
    WHEN (idproducto IS NOT NULL) THEN 'Producto'::text
    WHEN (idprendaservicio IS NOT NULL) THEN 'Servicio'::text
    ELSE NULL::text
END) STORED,
	CONSTRAINT "detallefactura_check" CHECK (((idprendaservicio IS NOT NULL) AND (idproducto IS NULL)) OR ((idprendaservicio IS NULL) AND (idproducto IS NOT NULL)))
);
--> statement-breakpoint
CREATE TABLE "prendaservicio" (
	"idprendaservicio" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "prendaservicio_idprendaservicio_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"idprenda" integer NOT NULL,
	"idservicio" integer NOT NULL,
	"preciounitario" numeric(10, 2) NOT NULL,
	CONSTRAINT "prendaservicio_idprenda_idservicio_key" UNIQUE("idprenda","idservicio")
);
--> statement-breakpoint
CREATE TABLE "productos" (
	"idproducto" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "productos_idproducto_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nombre" varchar(150) NOT NULL,
	"descripcion" text,
	"codigobarras" varchar(50),
	"precioventa" numeric(10, 2) NOT NULL,
	"costo" numeric(10, 2),
	"stockactual" integer DEFAULT 0 NOT NULL,
	"stockminimo" integer DEFAULT 0,
	"idcategoria" integer,
	"idestado" integer NOT NULL,
	"fechacreacion" timestamp DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "usuarios" (
	"idusuario" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "usuarios_idusuario_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nombre" varchar(100) NOT NULL,
	"apellido" varchar(100),
	"email" varchar(100),
	"username" varchar(50) NOT NULL,
	"passwordhash" varchar(255) NOT NULL,
	"idestado" integer NOT NULL,
	"fechacreacion" timestamp DEFAULT CURRENT_TIMESTAMP,
	"fechaultimologin" timestamp,
	"passwordresettoken" varchar(300),
	"passwordresettokenexpiry" timestamp,
	CONSTRAINT "usuarios_email_key" UNIQUE("email"),
	CONSTRAINT "usuarios_username_key" UNIQUE("username")
);
--> statement-breakpoint
CREATE TABLE "gastos" (
	"idgasto" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "gastos_idgasto_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"idcategoriagasto" integer NOT NULL,
	"monto" numeric(18, 2) NOT NULL,
	"fechagasto" timestamp NOT NULL,
	"descripcion" varchar(500),
	"referencia" varchar(200),
	"comprobanteurl" varchar(500),
	"idusuario" integer NOT NULL,
	"idestado" integer DEFAULT 1 NOT NULL,
	"fechacreacion" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"fechaultimaactualizacion" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "gastos_monto_check" CHECK (monto > (0)::numeric)
);
--> statement-breakpoint
CREATE TABLE "pagos" (
	"idpago" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pagos_idpago_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"idfactura" integer NOT NULL,
	"monto" numeric(10, 2) NOT NULL,
	"idestado" integer NOT NULL,
	"fechapago" timestamp DEFAULT CURRENT_TIMESTAMP,
	"fechaultima_actualizacion" timestamp DEFAULT CURRENT_TIMESTAMP,
	"metodopago" varchar(20) NOT NULL,
	"referencia" varchar(100),
	"idusuario" integer NOT NULL,
	"notas" text,
	CONSTRAINT "pagos_metodopago_check" CHECK ((metodopago)::text = ANY ((ARRAY['otro'::character varying, 'transferencia'::character varying, 'tarjeta'::character varying, 'efectivo'::character varying])::text[]))
);
--> statement-breakpoint
CREATE TABLE "prendas" (
	"idprenda" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "prendas_idprenda_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nombre" varchar(100) NOT NULL,
	"descripcion" text
);
--> statement-breakpoint
CREATE TABLE "servicios" (
	"idservicio" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "servicios_idservicio_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nombre" varchar(100) NOT NULL,
	"descripcion" text,
	"duracion_estimada" integer,
	"idestado" integer NOT NULL,
	"fecha_creacion" timestamp DEFAULT CURRENT_TIMESTAMP,
	"fechaultimaactualizacion" timestamp DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
CREATE TABLE "categoriasproducto" (
	"idcategoria" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "categoriasproducto_idcategoria_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nombre" varchar(50) NOT NULL
);
--> statement-breakpoint
CREATE TABLE "refreshtokens" (
	"idrefreshtokens" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "refreshtokens_idrefreshtokens_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"idusuario" integer NOT NULL,
	"token" varchar(500) NOT NULL,
	"expires" timestamp NOT NULL,
	"created" timestamp NOT NULL,
	"createdbyip" varchar(50) NOT NULL,
	"revoked" timestamp,
	"revokedbyip" varchar(50),
	"replacedbytoken" varchar(500)
);
--> statement-breakpoint
CREATE TABLE "roles" (
	"idrol" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "roles_idrol_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"nombre" varchar(50) NOT NULL,
	"descripcion" varchar(200),
	"idestado" integer NOT NULL,
	"fechacreacion" timestamp DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "roles_nombre_key" UNIQUE("nombre")
);
--> statement-breakpoint
CREATE TABLE "usuariorol" (
	"idusuario" integer NOT NULL,
	"idrol" integer NOT NULL,
	"fechaasignacion" timestamp DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT "usuariorol_pkey" PRIMARY KEY("idusuario","idrol")
);
--> statement-breakpoint
ALTER TABLE "categoriasgasto" ADD CONSTRAINT "fk_categoriasgasto_estados" FOREIGN KEY ("idestado") REFERENCES "public"."estados"("idestado") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "clientes" ADD CONSTRAINT "fk_clientes_estados" FOREIGN KEY ("idestado") REFERENCES "public"."estados"("idestado") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facturas" ADD CONSTRAINT "fk_facturas_clientes" FOREIGN KEY ("idcliente") REFERENCES "public"."clientes"("idcliente") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facturas" ADD CONSTRAINT "fk_facturas_estadoentrega" FOREIGN KEY ("idestadoentrega") REFERENCES "public"."estados"("idestado") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facturas" ADD CONSTRAINT "fk_facturas_estados" FOREIGN KEY ("idestado") REFERENCES "public"."estados"("idestado") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facturas" ADD CONSTRAINT "fk_facturas_usuarios" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("idusuario") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "detallefactura" ADD CONSTRAINT "fk_detallefactura_factura" FOREIGN KEY ("idfactura") REFERENCES "public"."facturas"("idfactura") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "detallefactura" ADD CONSTRAINT "fk_detallefactura_prendaservicio" FOREIGN KEY ("idprendaservicio") REFERENCES "public"."prendaservicio"("idprendaservicio") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "detallefactura" ADD CONSTRAINT "fk_detallefactura_producto" FOREIGN KEY ("idproducto") REFERENCES "public"."productos"("idproducto") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prendaservicio" ADD CONSTRAINT "fk_prendaservicio_prendas" FOREIGN KEY ("idprenda") REFERENCES "public"."prendas"("idprenda") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "prendaservicio" ADD CONSTRAINT "fk_prendaservicio_servicios" FOREIGN KEY ("idservicio") REFERENCES "public"."servicios"("idservicio") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "productos" ADD CONSTRAINT "fk_productos_categoriasproducto" FOREIGN KEY ("idcategoria") REFERENCES "public"."categoriasproducto"("idcategoria") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "productos" ADD CONSTRAINT "fk_productos_estados" FOREIGN KEY ("idestado") REFERENCES "public"."estados"("idestado") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "usuarios" ADD CONSTRAINT "fk_usuarios_estados" FOREIGN KEY ("idestado") REFERENCES "public"."estados"("idestado") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gastos" ADD CONSTRAINT "fk_gastos_categoriasgasto" FOREIGN KEY ("idcategoriagasto") REFERENCES "public"."categoriasgasto"("idcategoriagasto") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gastos" ADD CONSTRAINT "fk_gastos_estados" FOREIGN KEY ("idestado") REFERENCES "public"."estados"("idestado") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "gastos" ADD CONSTRAINT "fk_gastos_usuarios" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("idusuario") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pagos" ADD CONSTRAINT "fk_pagos_estados" FOREIGN KEY ("idestado") REFERENCES "public"."estados"("idestado") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pagos" ADD CONSTRAINT "fk_pagos_facturas" FOREIGN KEY ("idfactura") REFERENCES "public"."facturas"("idfactura") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pagos" ADD CONSTRAINT "fk_pagos_usuarios" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("idusuario") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "servicios" ADD CONSTRAINT "fk_servicios_estados" FOREIGN KEY ("idestado") REFERENCES "public"."estados"("idestado") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refreshtokens" ADD CONSTRAINT "fk_refreshtokens_usuarios" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("idusuario") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "roles" ADD CONSTRAINT "fk_roles_estados" FOREIGN KEY ("idestado") REFERENCES "public"."estados"("idestado") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "usuariorol" ADD CONSTRAINT "fk_usuariorol_roles" FOREIGN KEY ("idrol") REFERENCES "public"."roles"("idrol") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "usuariorol" ADD CONSTRAINT "fk_usuariorol_usuarios" FOREIGN KEY ("idusuario") REFERENCES "public"."usuarios"("idusuario") ON DELETE no action ON UPDATE no action;
*/